allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAge: 0

overrides:
  semver: ^7.5.4

packages:
  - .

shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
